version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: wrap_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: wrap_db
      POSTGRES_USER: wrap_admin
      POSTGRES_PASSWORD: wrap_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wrap_admin", "-d", "wrap_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: wrap_redis
    restart: always
    ports:
      - '63790:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
